### ISSUE TITLE
Build golang run-once Koffer entrypoint

### ISSUE THREAD

**Issue by usrbinkat** [CodeSparta/collector-meta#1]
[Low Side Meta Repo](https://github.com/RedShiftOfficial/collector-meta)

**Comment by kevindoingbizas** [comment]
Will be able to be consumed and executed by individuals other than the Red Hat team

**Comment by kevindoingbizas** [comment]
Currently 3 Manual steps.

**Comment by usrbinkat** [comment]
Resolved with entrypoint multi-plugin run once capability.
